### ISSUE TITLE
Plugin won't read "int" type

### ISSUE THREAD

**Issue by Pnoddy1** [johnpholden/qgis3redistricter#1]
I am trying to make a map using a shapefile and population data in an XLSX file. The first time I used the plugin using this data set worked fine, but I have now been receiving this error after restarting QGIS.

Here is the issue I am having:
1. Load shapefile
2. Load XLSX with population field
3. Join shapefile and XLSX
4. Load plugin
5. Make plan and select appropriate fields
6. "TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"

QGIS reads the population field as an "int" type. The district and data fields are "QString" types. Is this an issue with the plugin or the data set?

**Comment by johnpholden** [comment]
My initial guess is this is a data error as it's being read as a NoneType.
Do you have an exact copy of the error message, including the code line
where the plugin fails?

Cheers
John

**Comment by Pnoddy1** [comment]
I added a new field for the district and it seems to work now. If I get the issue again, I will post a screenshot.

**Comment by johnpholden** [comment]
Cheers. Hope you don't have any further issues!
