### ISSUE TITLE
Python error when creating plan

### ISSUE THREAD

**Issue by MazRad** [johnpholden/qgis3redistricter#10]
Hi
When I go to create a plan, I get a python error of:    
self.totalpop = self.totalpop + int(feature[self.popfield])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'QVariant'

I'm using StatsCan boundary and census data.

**Comment by johnpholden** [comment]
Hi, it looks like your population field isn't always defined as a number. I'll fix the plugin to handle the error better.

**Comment by MazRad** [comment]
Got it! Had a sneaky null value in there

**Comment by johnpholden** [comment]
Fantastic! Let me know if you have any more issues, an update will be sorted shortly
