### ISSUE TITLE
'Update selected polygons' has no visible effect

### ISSUE THREAD

**Issue by cmsmcq** [johnpholden/qgis3redistricter#13]
Thank you for the plugin!

After some difficulties creating a new plan (Python errors on creation and loading of plans -- when I started fresh with a clean new layer, in order to file an issue, I could not reproduce them), I am now having difficulties assigning precincts to districts.  

It is possible (or likely) that I have just done something unexpected and wrong.

For work on a municipal redistricting, I have taken the precinct shapefile from the Secretary of State, done a Feature Filter query to restrict it to the relevant county, exported the features to KML, and manually deleted precincts from the KML which lie outside the city limits.  (I work with XML and KML regularly, and am confident I did not accidentally corrupt the KML data.) In the plugin, I have created a new plan with 9 districts, adding a new attribute for the district data.  The plugin pane shows 600,000 voters (give or take) in District 0 Unassigned, an 800% deviation, and 0 voters in each of districts 1-9, a 100% deviation.  It all looks plausible and correct.

My first exercise will be reproducing the existing districts, so I have a layer imported from elsewhere, showing the existing district boundaries, and I set the redistricting layer to 30% opacity so the status quo districts shine through and I can assign precincts to districts.  Selecting a precinct works fine.  Either before or after selecting one or more precincts, I can set the Active District to the correct value.  Then I click 'Update selected polygons', and the selection is cleared.  No change to the display of the precinct, no change to the population totals or deviations of the district I'm trying to assign them to or to Unassigned.
Since QGIS is displaying log messages, I can see that when I click 'Update selected polygons', a log message beginning with a time stamp and continuing `WARNING    {'': , '1': , '2': , '3': , '4': , '5': , '6': , '7': , '8': , '9': }` is added to the General log window.  Nothing in the Python warning window.

Seeing from comments in issue 7 that testing may be better with some formats or others, I guess my next step is to see if I can convert the KML to a shapefile and reproduce the problem.

**Comment by cmsmcq** [comment]
When the redistricting layer is a shapefile, things appear to be working as expected.  So while I hope you get a chance to find and fix the bug involving KML files, I have an acceptable workaround.

**Comment by johnpholden** [comment]
Thank you for the report!

Unfortunately after a look the plugin does not work with KML files - QGIS cannot update a KML attribute table due to its data structure, it can only add or remove shapes, which breaks the plugin's functionality. Exporting to a shapefile, geodatabase, or editable format is the work-around.
