### ISSUE TITLE
Experimental branch won't load

### ISSUE THREAD

**Issue by leehach** [johnpholden/qgis3redistricter#2]
Not sure if you want issue reports on **experimental** branch, but I saw John speak at QGIS NA 2020 and he recommended using experimental because of a recently fixed memory leak. Unfortunately, I can't get it to load. *I have downloaded master and installed and loaded successfully.*

Error in experimental comes when trying to initialize the plugin from the toolbar button or Plugins menu item. A dialog box appears with:

> **Attribute Error:**
> 
> 'StattoRedistrictDockWidget' object has no attribute 'btnCurrentPlan'
> 
> run[StattoRedistrict.py:430]

The error line is:

```python
            self.dockwidget.btnCurrentPlan.clicked.connect(self.loadActivePlanParametersDialog)
```

Platform info:

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Linux Mint 19.1
Active python plugins | GeoCoding; tiss; DotMap; quick_map_services; qgis3redistricter-master; QuickWKT; Socrata; BivariateLegend; postgisQueryBuilder; mmqgis; firstaid; MetaSearch; db_manager; processing

**Comment by johnpholden** [comment]
I'll take a look and get it sorted, cheers!

John

**Comment by johnpholden** [comment]
Apologies this took awhile, but should be fixed now (positively identified issue/fix applied/problem went away.)

John
